// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Nier

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Buttons struct {
	_tab flatbuffers.Table
}

func GetRootAsButtons(buf []byte, offset flatbuffers.UOffsetT) *Buttons {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Buttons{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsButtons(buf []byte, offset flatbuffers.UOffsetT) *Buttons {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Buttons{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Buttons) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Buttons) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Buttons) Buttons(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *Buttons) ButtonsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Buttons) MutateButtons(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func ButtonsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ButtonsAddButtons(builder *flatbuffers.Builder, buttons flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(buttons), 0)
}
func ButtonsStartButtonsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ButtonsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
