// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Nier

import "strconv"

type PacketType uint32

const (
	PacketTypeID_MASTER_CLIENT_START PacketType = 0
	PacketTypeID_SPAWN_ENTITY        PacketType = 1
	PacketTypeID_DESTROY_ENTITY      PacketType = 2
	PacketTypeID_ENTITY_DATA         PacketType = 3
	PacketTypeID_MASTER_CLIENT_END   PacketType = 4
	PacketTypeID_SERVER_START        PacketType = 2048
	PacketTypeID_SERVER_END          PacketType = 2049
	PacketTypeID_CLIENT_START        PacketType = 4096
	PacketTypeID_PLAYER_DATA         PacketType = 4097
	PacketTypeID_ANIMATION_START     PacketType = 4098
	PacketTypeID_CHANGE_PLAYER       PacketType = 4099
	PacketTypeID_BUTTONS             PacketType = 4100
	PacketTypeID_CLIENT_END          PacketType = 4101
	PacketTypeID_PING                PacketType = 32768
	PacketTypeID_PONG                PacketType = 32769
)

var EnumNamesPacketType = map[PacketType]string{
	PacketTypeID_MASTER_CLIENT_START: "ID_MASTER_CLIENT_START",
	PacketTypeID_SPAWN_ENTITY:        "ID_SPAWN_ENTITY",
	PacketTypeID_DESTROY_ENTITY:      "ID_DESTROY_ENTITY",
	PacketTypeID_ENTITY_DATA:         "ID_ENTITY_DATA",
	PacketTypeID_MASTER_CLIENT_END:   "ID_MASTER_CLIENT_END",
	PacketTypeID_SERVER_START:        "ID_SERVER_START",
	PacketTypeID_SERVER_END:          "ID_SERVER_END",
	PacketTypeID_CLIENT_START:        "ID_CLIENT_START",
	PacketTypeID_PLAYER_DATA:         "ID_PLAYER_DATA",
	PacketTypeID_ANIMATION_START:     "ID_ANIMATION_START",
	PacketTypeID_CHANGE_PLAYER:       "ID_CHANGE_PLAYER",
	PacketTypeID_BUTTONS:             "ID_BUTTONS",
	PacketTypeID_CLIENT_END:          "ID_CLIENT_END",
	PacketTypeID_PING:                "ID_PING",
	PacketTypeID_PONG:                "ID_PONG",
}

var EnumValuesPacketType = map[string]PacketType{
	"ID_MASTER_CLIENT_START": PacketTypeID_MASTER_CLIENT_START,
	"ID_SPAWN_ENTITY":        PacketTypeID_SPAWN_ENTITY,
	"ID_DESTROY_ENTITY":      PacketTypeID_DESTROY_ENTITY,
	"ID_ENTITY_DATA":         PacketTypeID_ENTITY_DATA,
	"ID_MASTER_CLIENT_END":   PacketTypeID_MASTER_CLIENT_END,
	"ID_SERVER_START":        PacketTypeID_SERVER_START,
	"ID_SERVER_END":          PacketTypeID_SERVER_END,
	"ID_CLIENT_START":        PacketTypeID_CLIENT_START,
	"ID_PLAYER_DATA":         PacketTypeID_PLAYER_DATA,
	"ID_ANIMATION_START":     PacketTypeID_ANIMATION_START,
	"ID_CHANGE_PLAYER":       PacketTypeID_CHANGE_PLAYER,
	"ID_BUTTONS":             PacketTypeID_BUTTONS,
	"ID_CLIENT_END":          PacketTypeID_CLIENT_END,
	"ID_PING":                PacketTypeID_PING,
	"ID_PONG":                PacketTypeID_PONG,
}

func (v PacketType) String() string {
	if s, ok := EnumNamesPacketType[v]; ok {
		return s
	}
	return "PacketType(" + strconv.FormatInt(int64(v), 10) + ")"
}
