// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Nier

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerData struct {
	_tab flatbuffers.Struct
}

func (rcv *PlayerData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerData) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *PlayerData) Flashlight() bool {
	return rcv._tab.GetBool(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *PlayerData) MutateFlashlight(n bool) bool {
	return rcv._tab.MutateBool(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *PlayerData) Speed() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *PlayerData) MutateSpeed(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *PlayerData) Facing() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *PlayerData) MutateFacing(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *PlayerData) Facing2() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *PlayerData) MutateFacing2(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *PlayerData) WeaponIndex() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *PlayerData) MutateWeaponIndex(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *PlayerData) PodIndex() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(20))
}
func (rcv *PlayerData) MutatePodIndex(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(20), n)
}

func (rcv *PlayerData) HeldButtonFlags() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(24))
}
func (rcv *PlayerData) MutateHeldButtonFlags(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(24), n)
}

func (rcv *PlayerData) Position(obj *Vector3f) *Vector3f {
	if obj == nil {
		obj = new(Vector3f)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+28)
	return obj
}

func CreatePlayerData(builder *flatbuffers.Builder, flashlight bool, speed float32, facing float32, facing2 float32, weaponIndex uint32, podIndex uint32, heldButtonFlags uint32, position_x float32, position_y float32, position_z float32) flatbuffers.UOffsetT {
	builder.Prep(4, 40)
	builder.Prep(4, 12)
	builder.PrependFloat32(position_z)
	builder.PrependFloat32(position_y)
	builder.PrependFloat32(position_x)
	builder.PrependUint32(heldButtonFlags)
	builder.PrependUint32(podIndex)
	builder.PrependUint32(weaponIndex)
	builder.PrependFloat32(facing2)
	builder.PrependFloat32(facing)
	builder.PrependFloat32(speed)
	builder.Pad(3)
	builder.PrependBool(flashlight)
	return builder.Offset()
}
