// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nier

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerPacket struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerPacket(buf []byte, offset flatbuffers.UOffsetT) *PlayerPacket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerPacket{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPlayerPacket(buf []byte, offset flatbuffers.UOffsetT) *PlayerPacket {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerPacket{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *PlayerPacket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerPacket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerPacket) Guid() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerPacket) MutateGuid(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *PlayerPacket) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PlayerPacket) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PlayerPacket) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PlayerPacket) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func PlayerPacketStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PlayerPacketAddGuid(builder *flatbuffers.Builder, guid uint64) {
	builder.PrependUint64Slot(0, guid, 0)
}
func PlayerPacketAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func PlayerPacketStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PlayerPacketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
