// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nier

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetMasterClient struct {
	_tab flatbuffers.Struct
}

func (rcv *SetMasterClient) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetMasterClient) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *SetMasterClient) Guid() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *SetMasterClient) MutateGuid(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateSetMasterClient(builder *flatbuffers.Builder, guid uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 8)
	builder.PrependUint64(guid)
	return builder.Offset()
}
