// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nier

import "strconv"

type VersionMajor uint32

const (
	VersionMajorValue VersionMajor = 1
)

var EnumNamesVersionMajor = map[VersionMajor]string{
	VersionMajorValue: "Value",
}

var EnumValuesVersionMajor = map[string]VersionMajor{
	"Value": VersionMajorValue,
}

func (v VersionMajor) String() string {
	if s, ok := EnumNamesVersionMajor[v]; ok {
		return s
	}
	return "VersionMajor(" + strconv.FormatInt(int64(v), 10) + ")"
}
