// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nier

import "strconv"

type VersionMinor uint32

const (
	VersionMinorValue VersionMinor = 0
)

var EnumNamesVersionMinor = map[VersionMinor]string{
	VersionMinorValue: "Value",
}

var EnumValuesVersionMinor = map[string]VersionMinor{
	"Value": VersionMinorValue,
}

func (v VersionMinor) String() string {
	if s, ok := EnumNamesVersionMinor[v]; ok {
		return s
	}
	return "VersionMinor(" + strconv.FormatInt(int64(v), 10) + ")"
}
