// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nier

import "strconv"

type VersionPatch uint32

const (
	VersionPatchValue VersionPatch = 0
)

var EnumNamesVersionPatch = map[VersionPatch]string{
	VersionPatchValue: "Value",
}

var EnumValuesVersionPatch = map[string]VersionPatch{
	"Value": VersionPatchValue,
}

func (v VersionPatch) String() string {
	if s, ok := EnumNamesVersionPatch[v]; ok {
		return s
	}
	return "VersionPatch(" + strconv.FormatInt(int64(v), 10) + ")"
}
